name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
version-template: '$COMPLETE'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&#@`'
template: |
  # Release v$NEXT_MINOR_VERSION

  $CHANGES
exclude-labels:
  - 'kind/skip-release-notes'