name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$COMPLETE'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&#@`'
template: |
  # Release v$RESOLVED_VERSION

  $CHANGES
exclude-labels:
  - 'kind/skip-release-notes'
  - 'dev/wont-fix'
  - 'component/github-actions'
categories:
  - title: '☠ Breaking Changes ☠'
    labels:
    - 'BREAKING CHANGE!!!'
  - title: '🚀 Features'
    labels:
    - 'kind/epic'
    - 'kind/feature'
    - 'kind/poc'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    labels:
    - 'kind/fix'
  - title: '📄 Documentation'
    collapse-after: 5
    labels:
    - 'kind/documentation'
  - title: '🥺 Deprecation'
    collapse-after: 3
    labels:
    - 'kind/deprecation'
  - title: '🧰 Maintenance'
    collapse-after: 3
    labels:
    - 'kind/chore'
    - 'kind/refactor'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
    - 'kind/dependency'
