name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$COMPLETE'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&#@`'
template: |
  # Release v$RESOLVED_VERSION

  $CHANGES
exclude-labels:
  - 'kind/skip-release-notes'
  - 'wontfix'
  - 'triage/wont-fix'
  - 'triage/invalid'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    labels:
      - 'kind/bug'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 3
    labels:
      - 'chore'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
