# These settings are synced to GitHub by https://github.com/github/safe-settings?tab=readme-ov-file#github-safe-settings

# Milestones: define milestones for Issues and Pull Requests
milestones:
- title: 2024-Q4
  #description: milestone-description
  # The state of the milestone. Either `open` or `closed`
  state: closed

- title: 2025-Q1
  state: open

- title: 2025-Q2
  state: open

- title: 2025-Q3
  state: open

- title: 2025-Q4
  state: open

- title: 2026-Q1
  state: open
