linters:
  disable:
    - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/open-component-model/ocm
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"

issues:
  exclude:
    - composites
