ARG ALPINE_VERSION=latest
ARG OCM_VERSION=v0.2.0
ARG OCM_PLATFORM=Linux_x86_64

FROM alpine:${ALPINE_VERSION}
ARG ALPINE_VERSION
ARG OCM_VERSION
ARG OCM_PLATFORM
WORKDIR /tmp
RUN echo OCM_VERSION: ${OCM_VERSION}, OCM_PLATFORM: ${OCM_PLATFORM}
RUN wget https://github.com/open-component-model/ocm/releases/download/${OCM_VERSION}/ocm_${OCM_PLATFORM}.tar.gz
RUN tar xzf ocm_${OCM_PLATFORM}.tar.gz

FROM alpine:${ALPINE_VERSION}
ARG ALPINE_VERSION
ARG OCM_VERSION
ARG OCM_PLATFORM
WORKDIR /root/
COPY --from=0 /tmp/ocm /usr/bin/ocm
