#!/bin/bash

NAME="$(basename "$0")"

Error() {
  echo '{ "error": "'$1'" }' >&2
  exit 1
}

Info() {
  echo '{"version":"v1","pluginName":"'$NAME'","pluginVersion":"v1","shortDescription":"a test plugin","description":"a test plugin with access method test","accessMethods":[{"name":"identity","shortDescription":"test access","description":"","supportContentIdentity":true}]}
'
}

Get() {
  echo "test content"
}

Validate() {
  echo '{"short":"a test","mediaType":"plain/text","description":"","hint":"testfile","consumerId":{"hostname":"localhost","type":"identity"}}'
}

AccessMethod() {
  case "$1" in
    get) Get "${@:2}";;
    validate) Validate "${@:2}";;
    identity) Identity;;
    *) Error "invalid accessmethod command $1";;
  esac
}

Identity() {
  echo "testidentity"
}

case "$1" in
  info) Info;;
  accessmethod) AccessMethod "${@:2}";;
  *) Error "invalid command $1";;
esac