chart:
  resource:
    name: chart

imageMapping:
  - tag: image.tag
    repository: image.repository
    resource:
      name: image

kubeConfigName: target
release: echoserver
createNamespace: true

# default helm values can be provided here. They will override any values given in the
# configTemplate from the packagespec.yaml
values:
  replicaCount: 2
  ingress:
    enabled: false