#!/bin/bash -e

NAME="$(basename "$0")"

Error() {
  echo '{ "error": "'$1'" }' >&2
  exit 1
}

extract() {
   v="$(echo "$2" | sed 's/.*"'"$1"'": *"\([^"]*\)".*/\1/')"
  if [ "$v" != "$2" ]; then
     echo "$v"
  fi
}

setfield() {
  local v
  s="$(echo "$2" | sed 's/\//\\\//g')"
  v="$(echo "$BASE" | sed 's/"'"$1"'": *"[^"]*"/"'"$1"'":"'"$s"'"/')"
  if [ "$v" == "$BASE" ]; then
    v="$(echo "$BASE" | sed 's/^{"/{"'"$1"'":"'"$s"'","/')"
  fi
  if [ "$v" == "$BASE" ]; then
    v="$(echo "$BASE" | sed 's/^{/{"'"$1"'":"'"$s"'"/')"
  fi
  BASE="$v"
}

setopt() {
  local v
  v="$(extract "$1" "$OPTS")"
  if [ -n "$v" ]; then
    setfield "$2" "$v"
  fi
}

Info() {
  PATHOPT='{"name":"accessPath","type":"string","description":"file path"}'
  MEDIAOPT='{"name":"mediaType"}'
  OPTS='['$PATHOPT','$MEDIAOPT']'
  echo '{"version":"v1","pluginName":"'$NAME'","pluginVersion":"v1","shortDescription":"a test plugin","description":"a test plugin with access method test","accessMethods":[{"name":"test","shortDescription":"test access","description":"","options":'$OPTS'},{"name":"test","version":"v1","shortDescription":"test access","description":""}]}
'
}

Get() {
  echo "test content"
  for arg; do
    echo "$arg"
  done
}

Validate() {
  echo '{"short":"a test","mediaType":"plain/text","description":"","hint":"testfile","consumerId":{"hostname":"localhost","type":"test"}}'
}

Compose() {
  BASE="$3"
  OPTS="$2"

  setopt accessPath path
  setopt mediaType mediaType
  echo "$BASE"
}

AccessMethod() {
  case "$1" in
    get) Get "${@:2}";;
    validate) Validate "${@:2}";;
    compose) Compose "${@:2}";;
    *) Error "invalid accessmethod command $1";;
  esac
}

case "$1" in
  info) Info;;
  accessmethod) AccessMethod "${@:2}";;
  *) Error "invalid command $1";;
esac
