#!/bin/bash

NAME="$(basename "$0")"

Error() {
  echo '{ "error": "'$1'" }' >&2
  exit 1
}

Info() {
  echo '{"version":"v1","pluginName":"'$NAME'","pluginVersion":"v1","shortDescription":"a test plugin","description":"a test plugin with value merge algorithm acme.org/test","valueMergeHandlers":[{"name":"acme.org/test","description":"test merger"}],"labelMergeSpecifications":[{"name":"testlabel","description":"generic testlabel merge spec","algorithm":"default"},{"name":"testlabel","version":"v2","description":"v2 testlabel merge spec","algorithm":"simpleMapMerge"}]}
'
}

Execute() {
  echo '{"modified":true, "value":{"mode":"resolved"},"message":"all good"}'
}

ValueMergeHandler() {
  case "$1" in
    execute) Execute "${@:2}";;
    *) Error "invalid accessmethod command $1";;
  esac
}

case "$1" in
  info) Info;;
  valuemergehandler) ValueMergeHandler "${@:2}";;
  *) Error "invalid command $1";;
esac
