name: Set milestone
on:
  issues:
    types:
    - closed
  pull_request:
    types:
    - closed

jobs:
  set_milestone:
    uses: open-component-model/.github/.github/workflows/milestone.yml@main
    secrets: inherit
    permissions:
      issues: write
      pull-requests: write
