name: PR Labeler
on:
- pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/config/labeler.yml
      - name: Label PR based on branch name
        uses: actions/labeler@v5
        with:
          configuration-path: .github/config/labeler.yml