name: Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Markdown Linting
        uses: nosborn/github-action-markdown-cli@508d6cefd8f0cc99eab5d2d4685b1d5f470042c1 # v3.5.0
        with:
          files: .
          dot: true
          config_file: .github/config/markdownlint.yml
          ignore_path: .github/config/markdownignore
  verify-links:
    name: Verify links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Markdown verify links
        uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
        with:
          use-quiet-mode: yes
          use-verbose-mode: no
          config-file: .github/config/markdown-link-check.json
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@fcc5ca8351f0590978f238d6babfe3f28afc361f # 0.65.0
        with:
          config_path: .github/config/spellcheck.yml
          task_name: Markdown

